name: Build Java with Native C (JNI)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Java and GCC
      run: |
        sudo apt-get update
        sudo apt-get install default-jdk gcc -y

    - name: Unzip source.zip
      run: unzip ParrotCheatsold.zip -d ./unzipped

    - name: Compile native C to .so
      run: |
        cd unzipped/native
        gcc -c -fPIC -I${JAVA_HOME}/include -I${JAVA_HOME}/include/linux native-lib.c
        gcc -shared -o libnative-lib.so native-lib.o

    - name: Compile Java classes with JNI header
      run: |
        cd unzipped
        javac -h native NativeLib.java Main.java

    - name: Run Java program
      run: |
        cd unzipped
        java -Djava.library.path=native Main
